### PR TITLE
754 unit testing on bilbomd UI

### PR DESCRIPTION
**Pull request by shrprabh**
This pull request includes a comprehensive suite of tests for various components and functionalities in the application. The most important changes include adding tests for Redux store setup, various form components, and utility components to ensure they function correctly and handle edge cases.

### Tests for Redux Store and Hooks:

* [`src/app/hooks.test.tsx`](diffhunk://#diff-11c7ce00f4b1e7a6da364ffd51595d4bcaa130c86167c3542dc3e435a000395eR1-R25): Added tests for the `useAppDispatch` hook to ensure it returns the correct dispatch function.
* [`src/app/store.test.tsx`](diffhunk://#diff-060d9b7b43bf8d63df7f6e664f8951f3173ad5c69b0343dd64590096ff018d24R1-R34): Added tests for the Redux store to verify the correct reducers are initialized and the store initializes with preloaded state.

### Tests for Form Components:

* [`src/components/ConstInpForm/FormFields/FileField.test.tsx`](diffhunk://#diff-f30d6f3163c2c7b6b3934c03914fac653283c79cf69353bd081c4d46d9405763R1-R111): Added tests for the `FileField` component to verify file upload functionality, error handling, and multiple file processing.
* [`src/components/ConstInpForm/FormModel/formInitialValues.test.tsx`](diffhunk://#diff-2aa3c7047f3d69a74b0182d6bf27385e63a6f1e0a2b8d7648ad224163b2b5568R1-R66): Added tests to validate the structure of initial form values.
* [`src/components/ConstInpForm/FormModel/formModel.test.tsx`](diffhunk://#diff-9b3745d0b1bc097c8465e86c377b6c0616fb4a9fef6ee5a5c39aa169863f8e4bR1-R41): Added tests to verify the structure and properties of the form model.
* [`src/components/ConstInpForm/FormModel/validationSchemas.test.tsx`](diffhunk://#diff-191257625520321176ce9b11bfaa74874b0ac99d89c11b9db4523e6af08f6faaR1-R152): Added tests to validate file upload schema and rigid domain schema, ensuring proper validation rules are enforced.

### Tests for Utility Components:

* [`src/components/Common/CopyToClipboardButton.test.tsx`](diffhunk://#diff-1fafe8a8ae5993c93c2aefcae31b7999f7633611f0d5ebaa755cd14e6562af27R1-R48): Added tests for the `CopyToClipboardButton` component to verify text copying functionality and snackbar display.
* [`src/components/Debug.test.tsx`](diffhunk://#diff-41c458bad19ad2d7093cfcf8aa8efde9ccbfc54677190a8323fcb99d0e5d88c7R1-R63): Added tests for the `Debug` component to ensure it renders the Formik state header correctly.
* [`src/components/ErrorFallback.test.tsx`](diffhunk://#diff-c2faaf7a4ae2deda9e4c115fbb2a191362622e308898c95916ece0b903ed41a1R1-R23): Added tests for the `ErrorFallback` component to verify error message rendering and alert role.
* [`src/components/HeaderBox.test.tsx`](diffhunk://#diff-678c04a28755f85b640f228064a906f9e2a593d28868d0c3b4acd3f45cb8ddd1R1-R42): Added tests for the `HeaderBox` component to ensure it renders children and applies default styles correctly.
* [`src/components/Loadable.test.tsx`](diffhunk://#diff-c4a11ce9738428937ec67af9a331c46b7651b0e78c3e4f885909161a428abe53R1-R48): Added tests for the `Loadable` component to verify loader display and component rendering once loaded.
* [`src/components/Loader.test.tsx`](diffhunk://#diff-232c4d4b7a0bd41b940a4bffeb69e1eab98f4accfe2d2bf8eb848f345e76a1f5R1-R25): Added tests for the `Loader` component to ensure the `LinearProgress` bar renders and applies correct styles.
* [`src/components/Missing.test.tsx`](diffhunk://#diff-1c1669fe280f193089b28bd4886f5902881d150f067c840d3074744b17dbd15eR1-R15): Added tests for the `Missing` component to verify the 404 image renders with correct alt text.

### CODE REVIEW

**Comment by shrprabh** [comment]
**Current** **Test Coverage and Execution Report**

- **Test Execution:**
  - **Files Tested:** 35 (All passed ✅)
  - **Test Cases:** 103 (All passed ✅)
  - **Execution Time:** 26.43s (Transform: 6.96s, Setup: 10.99s, Collect: 30.94s, Tests: 10.86s, Environment: 14.84s, Prepare: 3.65s)

- **Code Coverage:**
  - **Overall Coverage:**
    - Statements: **20.72%**
    - Branches: **55.75%**
    - Functions: **39.30%**
    - Lines: **20.72%**
Will update here for further tests.

**Comment by dsclassen** [comment]
Can you please move all tests into `__tests__` directories. Similar to what we have done in the various features directories

**Comment by shrprabh** [comment]
Thank you, @dsclassen If the directory contains only a single file, we create a unit test case for that file. However, if the directory has more than one file, we create a __tests__ directory within that specific feature or component directory. I have updated my approach to maintain consistency, and I will continue to follow this convention for future tests.

**Comment by shrprabh** [comment]
image
Attaching the sample tree.

**Comment by dsclassen** [comment]
> Hello @dsclassen,
> 
> Can we implement pre-commit checks to guarantee that unit tests are successful before code commits. To accomplish this, we can utilize Git hooks, specifically a pre-commit hook using Husky (https://github.com/typicode/husky). By raising this suggestion, we can ensure that when we commit, we are not introducing any code breaks. If any breaks are found, we can address them directly during the commit process. What are your thoughts on this suggestion?

The pre-commit hooks are triggered on out local dev machines? I think this is a good idea. Let's try it.

Can we also implement a GitHub Action to run the tests when we merge to `main` ? Maybe this is redundent if we are assuring that a pre-commit hook has already run the tests...?

**Comment by shrprabh** [comment]
**Can we add a GitHub Action to run tests when merging to main? This might be redundant if we ensure pre-commit hooks run the tests.**?
- Pre-commit hooks on local machines catch issues early, but we can bypass them with the —no-verify option, compromising code quality. but still we can incorporate it because its a good idea.
- We can create a new CICD workflow file to run npm run test when a user raises a pull request.

**Comment by shrprabh** [comment]
I’ve added asynchronous loading and component updates. Can you pass the tests from your side @dsclassen ?

**Review by dsclassen — APPROVED** [review]
lgtm

**Pull request merged**
